version: '3'

services:
  db:
    image: mysql:8.0
    container_name: videopujcovna
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: videopujcovna
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_db:/var/lib/mysql
